"""sync schema projets salles

Revision ID: 84c43b7d26ae
Revises: d4e7f1b2c3a5
Create Date: 2026-10-08 23:17:05.061709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84c43b7d26ae'
down_revision: Union[str, None] = 'd4e7f1b2c3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ─────────────────────────────────────────────────────────────
    # budgets_formation
    # ─────────────────────────────────────────────────────────────
    op.add_column('budgets_formation',
        sa.Column('cout_supports', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('budgets_formation',
        sa.Column('valide', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('budgets_formation',
        sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()))
    op.drop_constraint('budgets_formation_projet_id_fkey', 'budgets_formation', type_='foreignkey')
    op.drop_constraint('budgets_formation_valide_par_fkey', 'budgets_formation', type_='foreignkey')
    op.create_foreign_key(None, 'budgets_formation', 'users', ['valide_par'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'budgets_formation', 'projets', ['projet_id'], ['id'], ondelete='CASCADE')
    op.drop_column('budgets_formation', 'cout_support')

    # ─────────────────────────────────────────────────────────────
    # candidats / entretiens — drop indexes
    # ─────────────────────────────────────────────────────────────
    op.drop_index('idx_candidats_decision', table_name='candidats')
    op.drop_index('idx_candidats_formateur', table_name='candidats')

    # ─────────────────────────────────────────────────────────────
    # documents
    # ─────────────────────────────────────────────────────────────
    op.alter_column('documents', 'contenu',
               existing_type=sa.TEXT(),
               nullable=True)

    # ─────────────────────────────────────────────────────────────
    # edt_sessions
    # ─────────────────────────────────────────────────────────────
    op.alter_column('edt_sessions', 'module',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index('idx_edt_projet', table_name='edt_sessions')
    op.drop_constraint('edt_sessions_projet_id_fkey', 'edt_sessions', type_='foreignkey')
    op.drop_constraint('edt_sessions_salle_id_fkey', 'edt_sessions', type_='foreignkey')
    op.drop_constraint('edt_sessions_formateur_id_fkey', 'edt_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'edt_sessions', 'salles', ['salle_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'edt_sessions', 'formateurs', ['formateur_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'edt_sessions', 'projets', ['projet_id'], ['id'], ondelete='CASCADE')
    op.drop_column('edt_sessions', 'code_session')
    op.drop_column('edt_sessions', 'type_activite')
    op.drop_column('edt_sessions', 'duree_minutes')
    op.drop_column('edt_sessions', 'numero_jour')
    op.drop_column('edt_sessions', 'jour_semaine')
    op.drop_column('edt_sessions', 'objectifs')

    # ─────────────────────────────────────────────────────────────
    # entretiens — drop index
    # ─────────────────────────────────────────────────────────────
    op.drop_index('idx_entretiens_candidat', table_name='entretiens')

    # ─────────────────────────────────────────────────────────────
    # formateurs — colonnes texte (longueurs)
    # ─────────────────────────────────────────────────────────────
    op.alter_column('formateurs', 'nom',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('formateurs', 'prenom',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('formateurs', 'email',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('formateurs', 'telephone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('formateurs', 'adresse',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('formateurs', 'specialite',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ─── FIX 1 : statut — retirer le default AVANT le cast, le remettre APRÈS ───
    op.alter_column('formateurs', 'statut', server_default=None)
    op.alter_column('formateurs', 'statut',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DISPONIBLE', 'OCCUPE', 'INACTIF', name='statutformateur'),
               nullable=False,
               postgresql_using='statut::statutformateur')
    op.alter_column('formateurs', 'statut',
               server_default=sa.text("'DISPONIBLE'::statutformateur"))

    # ─── FIX : nb_sessions — retirer le default AVANT le cast ───
    op.alter_column('formateurs', 'nb_sessions', server_default=None)
    op.alter_column('formateurs', 'nb_sessions',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('formateurs', 'nb_sessions',
               server_default=sa.text("'0'"))

    # ─── FIX 2 : recommandation — corriger la syntaxe (virgule orpheline) ───
    op.alter_column('formateurs', 'recommandation',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OUI', 'CONDITIONNEL', 'NON', name='recommandationevaluation'),
               existing_nullable=True,
               postgresql_using='recommandation::recommandationevaluation')

    op.alter_column('formateurs', 'date_creation',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_formateurs_specialite', table_name='formateurs')
    op.drop_index('idx_formateurs_statut', table_name='formateurs')
    op.drop_column('formateurs', 'disponible')
    op.drop_column('formateurs', 'commentaire')

    # ─────────────────────────────────────────────────────────────
    # offres — drop indexes
    # ─────────────────────────────────────────────────────────────
    op.drop_index('idx_offres_opportunite', table_name='offres')
    op.drop_index('idx_offres_statut', table_name='offres')

    # ─────────────────────────────────────────────────────────────
    # participants
    # ─────────────────────────────────────────────────────────────
    op.alter_column('participants', 'nom',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('participants', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('participants', 'entreprise',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ─────────────────────────────────────────────────────────────
    # projets — FIX 3 : ajout server_default sur NOT NULL
    # ─────────────────────────────────────────────────────────────
    op.add_column('projets', sa.Column('opportunite_id', sa.UUID(), nullable=True))
    op.add_column('projets', sa.Column('offre_id', sa.UUID(), nullable=True))
    op.add_column('projets',
        sa.Column('titre', sa.String(length=100), nullable=False, server_default='Sans titre'))
    op.add_column('projets', sa.Column('client', sa.String(length=100), nullable=True))
    op.add_column('projets',
        sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()))
    op.alter_column('projets', 'notes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('idx_projets_statut', table_name='projets')
    op.drop_constraint('projets_formateur_principal_id_fkey', 'projets', type_='foreignkey')
    op.drop_constraint('projets_salle_principale_id_fkey', 'projets', type_='foreignkey')
    op.drop_constraint('projets_tdr_id_fkey', 'projets', type_='foreignkey')
    op.drop_constraint('projets_marche_id_fkey', 'projets', type_='foreignkey')
    op.create_foreign_key(None, 'projets', 'opportunites', ['opportunite_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projets', 'offres', ['offre_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projets', 'resume_hebdomadaire')
    op.drop_column('projets', 'budget')
    op.drop_column('projets', 'client_id')
    op.drop_column('projets', 'formateur_principal_id')
    op.drop_column('projets', 'duree_totale_jours')
    op.drop_column('projets', 'salle_principale_id')
    op.drop_column('projets', 'nombre_modules')
    op.drop_column('projets', 'marche_id')
    op.drop_column('projets', 'tdr_id')

    # ─────────────────────────────────────────────────────────────
    # salles — FIX 3 : ajout server_default sur NOT NULL
    # ─────────────────────────────────────────────────────────────
    op.add_column('salles', sa.Column('equipements', sa.Text(), nullable=True))
    op.add_column('salles',
        sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()))
    op.alter_column('salles', 'nom',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('salles', 'adresse',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('salles', 'tarif_journalier',
               existing_type=sa.BOOLEAN(),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='tarif_journalier::int::float')
    op.drop_column('salles', 'commentaire')

    # ─────────────────────────────────────────────────────────────
    # seances / sessions
    # ─────────────────────────────────────────────────────────────
        # ─────────────────────────────────────────────────────────────
    # seances / sessions — nettoyer les NULL AVANT les SET NOT NULL
    # ─────────────────────────────────────────────────────────────

    # duree : 'Non précisée' pour les lignes NULL
    op.execute("UPDATE seances SET duree = 'Non précisée' WHERE duree IS NULL")
    op.alter_column('seances', 'duree',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=25),
               nullable=False)

    # theme : 'Non précisé' pour les lignes NULL
    op.execute("UPDATE seances SET theme = 'Non précisé' WHERE theme IS NULL")
    op.alter_column('seances', 'theme',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)

    # titre de sessions : déjà NOT NULL en théorie, mais au cas où
    op.execute("UPDATE sessions SET titre = 'Session sans titre' WHERE titre IS NULL")
    op.alter_column('sessions', 'titre',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)

    op.alter_column('sessions', 'client',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)

    # date_fin : copie date_debut pour les lignes NULL
    op.execute("UPDATE sessions SET date_fin = date_debut WHERE date_fin IS NULL")
    op.alter_column('sessions', 'date_fin',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'date_fin',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('sessions', 'client',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('sessions', 'titre',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('seances', 'theme',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('seances', 'duree',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('salles', sa.Column('commentaire', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('salles', 'tarif_journalier',
               existing_type=sa.Float(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               postgresql_using='tarif_journalier::boolean')
    op.alter_column('salles', 'adresse',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('salles', 'nom',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('salles', 'date_creation')
    op.drop_column('salles', 'equipements')
    op.add_column('projets', sa.Column('tdr_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projets', sa.Column('marche_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projets', sa.Column('nombre_modules', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projets', sa.Column('salle_principale_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projets', sa.Column('duree_totale_jours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projets', sa.Column('formateur_principal_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projets', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projets', sa.Column('budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projets', sa.Column('resume_hebdomadaire', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projets', type_='foreignkey')
    op.drop_constraint(None, 'projets', type_='foreignkey')
    op.create_foreign_key('projets_marche_id_fkey', 'projets', 'opportunites', ['marche_id'], ['id'])
    op.create_foreign_key('projets_tdr_id_fkey', 'projets', 'documents', ['tdr_id'], ['id'])
    op.create_foreign_key('projets_salle_principale_id_fkey', 'projets', 'salles', ['salle_principale_id'], ['id'])
    op.create_foreign_key('projets_formateur_principal_id_fkey', 'projets', 'formateurs', ['formateur_principal_id'], ['id'])
    op.create_index('idx_projets_statut', 'projets', ['statut'], unique=False)
    op.alter_column('projets', 'notes',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('projets', 'date_creation')
    op.drop_column('projets', 'client')
    op.drop_column('projets', 'titre')
    op.drop_column('projets', 'offre_id')
    op.drop_column('projets', 'opportunite_id')
    op.alter_column('participants', 'entreprise',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('participants', 'email',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('participants', 'nom',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_index('idx_offres_statut', 'offres', ['statut'], unique=False)
    op.create_index('idx_offres_opportunite', 'offres', ['opportunite_id'], unique=False)
    op.add_column('formateurs', sa.Column('commentaire', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('formateurs', sa.Column('disponible', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_index('idx_formateurs_statut', 'formateurs', ['statut'], unique=False)
    op.create_index('idx_formateurs_specialite', 'formateurs', ['specialite'], unique=False)
    op.alter_column('formateurs', 'date_creation',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('formateurs', 'recommandation',
               existing_type=sa.Enum('OUI', 'CONDITIONNEL', 'NON', name='recommandationevaluation'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               postgresql_using='recommandation::varchar')
    op.alter_column('formateurs', 'nb_sessions', server_default=None)
    op.alter_column('formateurs', 'nb_sessions',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('formateurs', 'nb_sessions', server_default=sa.text('0'))
    op.alter_column('formateurs', 'statut', server_default=None)
    op.alter_column('formateurs', 'statut',
               existing_type=sa.Enum('DISPONIBLE', 'OCCUPE', 'INACTIF', name='statutformateur'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               postgresql_using='statut::varchar')
    op.alter_column('formateurs', 'statut',
               server_default=sa.text("'DISPONIBLE'::character varying"))
    op.alter_column('formateurs', 'specialite',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('formateurs', 'adresse',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('formateurs', 'telephone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('formateurs', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('formateurs', 'prenom',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('formateurs', 'nom',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.create_index('idx_entretiens_candidat', 'entretiens', ['candidat_id'], unique=False)
    op.add_column('edt_sessions', sa.Column('objectifs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('edt_sessions', sa.Column('jour_semaine', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('edt_sessions', sa.Column('numero_jour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('edt_sessions', sa.Column('duree_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('edt_sessions', sa.Column('type_activite', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('edt_sessions', sa.Column('code_session', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'edt_sessions', type_='foreignkey')
    op.drop_constraint(None, 'edt_sessions', type_='foreignkey')
    op.drop_constraint(None, 'edt_sessions', type_='foreignkey')
    op.create_foreign_key('edt_sessions_formateur_id_fkey', 'edt_sessions', 'formateurs', ['formateur_id'], ['id'])
    op.create_foreign_key('edt_sessions_salle_id_fkey', 'edt_sessions', 'salles', ['salle_id'], ['id'])
    op.create_foreign_key('edt_sessions_projet_id_fkey', 'edt_sessions', 'projets', ['projet_id'], ['id'])
    op.create_index('idx_edt_projet', 'edt_sessions', ['projet_id'], unique=False)
    op.alter_column('edt_sessions', 'module',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('documents', 'contenu',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index('idx_candidats_formateur', 'candidats', ['formateur_id'], unique=False)
    op.create_index('idx_candidats_decision', 'candidats', ['decision_preselection'], unique=False)
    op.add_column('budgets_formation', sa.Column('cout_support', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'budgets_formation', type_='foreignkey')
    op.drop_constraint(None, 'budgets_formation', type_='foreignkey')
    op.create_foreign_key('budgets_formation_valide_par_fkey', 'budgets_formation', 'users', ['valide_par'], ['id'])
    op.create_foreign_key('budgets_formation_projet_id_fkey', 'budgets_formation', 'projets', ['projet_id'], ['id'])
    op.drop_column('budgets_formation', 'date_creation')
    op.drop_column('budgets_formation', 'valide')
    op.drop_column('budgets_formation', 'cout_supports')
    # ### end Alembic commands ###