"""Ajout de la colonne user_id et date_analyse dans le modèle historique_analyse

Revision ID: 90e0fbb8d168
Revises: 
Create Date: 2026-08-27 16:37:20.199674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90e0fbb8d168'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historique_analyses', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column(
        'historique_analyses',
        sa.Column('date_analyse', sa.DateTime(), nullable=False, server_default=sa.text('now()'))
    )
    op.create_foreign_key(None, 'historique_analyses', 'users', ['user_id'], ['id'])

    # Migration des colonnes vers les types ENUM correctement orthographiés (déjà existants en base)
    op.execute(
        "ALTER TABLE opportunites ALTER COLUMN source TYPE sourceopportunite "
        "USING source::text::sourceopportunite"
    )
    op.execute(
        "ALTER TABLE opportunites ALTER COLUMN statut TYPE statutopportunite "
        "USING statut::text::statutopportunite"
    )

    # Suppression des anciens types orphelins, maintenant inutilisés
    op.execute("DROP TYPE sourceoppotunite")
    op.execute("DROP TYPE statutoppoetunite")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE sourceoppotunite AS ENUM ('TEXTE', 'PDF', 'URL')"
    )
    op.execute(
        "CREATE TYPE statutoppoetunite AS ENUM ('EN_ATTENTE', 'ANALYSEE', 'ARCHIVEE')"
    )
    op.execute(
        "ALTER TABLE opportunites ALTER COLUMN source TYPE sourceoppotunite "
        "USING source::text::sourceoppotunite"
    )
    op.execute(
        "ALTER TABLE opportunites ALTER COLUMN statut TYPE statutoppoetunite "
        "USING statut::text::statutoppoetunite"
    )

    op.drop_constraint(None, 'historique_analyses', type_='foreignkey')
    op.drop_column('historique_analyses', 'date_analyse')
    op.drop_column('historique_analyses', 'user_id')
    # ### end Alembic commands ###